<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Intermediate Stata (Statistical Modeling) - 3&nbsp; One-sample t test</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04-regression.html" rel="next">
<link href="./02-visualization.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-univariate-analysis.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">One-sample t test</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Intermediate Stata</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-summarizing-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">(_dta has notes)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">02-visualization.html</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-univariate-analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">One-sample t test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">_cons | 5.113759 4.889846 1.05 0.299 -4.636317 14.86384</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-mixed-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">_cons | 1.644184 .0161148 102.03 0.000 1.612599 1.675768</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-survey-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">name type format label Variable label</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-multiple-imputation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">age | 142 12 12 | 154</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">lead Lead (mcg/dL)</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">One-sample t test</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><sup>#</sup> Univariate (and some Bivariate) Analysis</p>
<p>We start with analyzing single variables at a time, and then quickly discuss a chi-squared test which is a bivariate analysis. While these tests form the basis of many other methods, by themselves they are of limited us. All the tests we discuss here come with two very strong assumptions:</p>
<ol type="1">
<li>No other measured or unmeasured variables play a role in any relationship.</li>
<li>The relationship is the same for any subpopulation of your data.</li>
</ol>
<p>To see why these assumptions are so strong, lets consider the <a href="#two-sample-t-test">two-sample t-test</a>. We’ll discuss them in depth below, but the short version is that a two-sample t-test compares whether two groups have the same average value. If you were comparing average height between two groups, perhaps you’d find that one group was much taller than the other. But what if the shorter group was almost entirely made of children? We have no way of knowing whether the difference between groups is due to this or due to real differences.</p>
<p>For the second assumption, imagine some scenario where you have two groups. Among men, there is a large difference between groups, whereas among women, there is no difference between groups. On average (assuming a roughly 50/50 gender split), you’d see a moderate difference. But no one actually has a moderate difference! The two subgroups have different effects, so the two-sample t-test captures neither!</p>
<p>That said, there are a few situations where these tests are useful as stand-alone tests.</p>
<ol type="1">
<li>Exploratory/descriptive/pilot studies: Situations when are you not making strong claims, merely describing something you see in the data.</li>
<li>Very small sample sizes: While not ideal, small sample sizes can’t handle more complicated analysis, so these simple ones are all you have.</li>
<li>In randomized controlled experiments (such as in a lab): In these situations, you truly can ensure that both those assumptions are met. Just randomization is not sufficient, as the benefit of randomization is only guaranteed <em>theoretically</em> for <em>infinitely large samples</em>. Randomization helps a lot, but it’s not perfect!</li>
</ol>
<p>Reload the auto data set</p>
<pre><code>. sysuse auto, clear
(1978 automobile data)
</code></pre>
<p><sup>##</sup> One-sample t-test</p>
<p>A one-sample t-test tests whether the mean of a variable is equal to some constant. It is not needed a lot of the time (if we hypothesize that the average test score is 70, and every students get above an 80, why would we need to test this?), but we introduce it here just as a basis of further methods.</p>
<p>There are several assumptions necessary for a one-sample t-test, most of which are trivial/not that important. The two relatively important ones are</p>
<ol type="1">
<li>Independence. Each value must come from an independent source. If you have repeated measures (e.g.&nbsp;two different measures for the same person), this is violated. See the section of <a href="mixed-models.html">mixed models</a> for dealing with this sort of data.</li>
<li>The distribution of the <em>mean</em> is normal. Note that this assumption is <em>not</em> about the data itself. This assumption is valid if <em>either</em> the sample suggests that the data is normal (a bell-curve) <em>or</em> the sample size is large (above ~30)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. If this assumption does not hold, we generally still use the t-test, although there are tests called “non-parametric” tests which do not require this assumption. Not everyone is convinced they are necessary.</li>
</ol>
<p>There is no way to test the independence assumption, you must determine this based upon your knowledge of the data.</p>
<p>We can try and determine whether the normal distribution is valid for the data, but note that failing to find this does not imply the normality of the mean assumption is violated. This can be checked with a histogram or a qq-plot.</p>
<p>Let’s test whether the average mileage in the data is different from 20.</p>
<pre><code>. hist mpg, normal
(bin=8, start=12, width=3.625)
</code></pre>
<p><img src="Graph11.svg"></p>
<p>In a histogram, we are looking for violations from the bell-shape of a normal curve. We added the normal curve to the plot by the <code>normal</code> option. We can see that while the data is not perfectly normal, it also is not too far off. We can look at a qq-plot for further details.</p>
<pre><code>. qnorm mpg
</code></pre>
<p><img src="Graph12.svg"></p>
<p>With a qq-plot, we are looking for the points to roughly fall in a straight line, alone the 45-degree line. Here we see some mild violations of those, especially at either end.</p>
<p>Put together, this indicates that normality is not perfect, but its also not a terrible violation.</p>
<p>However, we don’t really care! The sample size is large enough that that assumption is valid. We can therefore perform our test using the <code>ttest</code> command.</p>
<pre><code>. ttest mpg == 20

Variable |     Obs        Mean    Std. err.   Std. dev.   [95% conf. interval]
---------+--------------------------------------------------------------------
     mpg |      74     21.2973    .6725511    5.785503     19.9569    22.63769
------------------------------------------------------------------------------
    mean = mean(mpg)                                              t =   1.9289
H0: mean = 20                                    Degrees of freedom =       73

    Ha: mean &lt; 20               Ha: mean != 20                 Ha: mean &gt; 20
 Pr(T &lt; t) = 0.9712         Pr(|T| &gt; |t|) = 0.0576          Pr(T &gt; t) = 0.0288
</code></pre>
<p>Our null hypothesis, the claim we are trying to see whether we have the evidence to reject, is that the average <code>mpg</code> in the population represented by this data is 20. We sometimes also just call 20, the value the null hypothesis is testing, the null hypothesis (e.g.&nbsp;“We are testing against the null hypothesis of 20.”).</p>
<p>Looking at the analysis, we see that we get some summary statistics. The 95% confidence interval represents the range which, if we were to draw repeated samples of the same size (74) from the population of all cars, we would expect 95% of the estimated means to fall in that range.</p>
<p>Below that, we see some details of the test being run. The important detail is that the null Hypothesis (<code>Ho</code>) is what you meant for it to be.</p>
<p>Finally, we get our p-values. There are three separate ones given for three different alternative hypotheses - testing whether the mean is less than 20, greater than 20, or simply not equal to 20. Each p-value represents the probability of observing a mean as extreme as the one we saw if 20 was the true population mean. In other words, we get the following three interpretations:</p>
<ul>
<li>There is 97.12% chance that if the true mean were 20, we would observe a sample mean of 21.2973 or lower.</li>
<li>There is 2.88% chance that if the true mean were 20, we would observe a sample mean of 21.2973 or higher.</li>
<li>There is 5.76% chance that if the true mean were 20, we would observe a sample mean of 21.2973 or higher <em>or</em> a sample mean of 18.7027 (this is calculated as 20 - (21.2973 - 20), in other words, 1.2973 below 20).</li>
</ul>
<p>The last interpretation (corresponding to <code>Ha: mean != 20</code> from the output) is known as the two-sided p-value, and should be your default. The other two, known as one-sided p-values, can be used if a priori you decide that you’re only interested in one direction.</p>
<p>The typical threshold used is p = .05, so we would fail to reject the null hypothesis (since .0576 &gt; .05), although this is extremely close to significant!</p>
<p>(Of course that first p-value &amp; interpretation is unnecessary - the observed test statistic is greater than 20, so there’s no chance we’d be able to make the argument that the true mean is less than 20!)</p>
<p><sup>##</sup> Two-sample t-test</p>
<p>While the one-sided t-test isn’t used very often, the two-sample version is. There are two different variations of it.</p>
<p><sup>###</sup> Independent</p>
<p>The independent two-sample t-test arises when you have two independent groups which have the same measurement, and you wish to test whether the mean of the two groups is equivalent. The same basic assumptions, independence (although here it’s both within group [each observation is independent from each other] and between groups [the two groups are independent, e.g.&nbsp;these are not repeated measures on the same person]) and normality of the mean.</p>
<p>For example in our data, we can test whether foreign and American cars have the same average mileage. We will again use the <code>ttest</code> command, though slightly differently.</p>
<pre><code>. ttest mpg, by(foreign)

Two-sample t test with equal variances
------------------------------------------------------------------------------
   Group |     Obs        Mean    Std. err.   Std. dev.   [95% conf. interval]
---------+--------------------------------------------------------------------
Domestic |      52    19.82692     .657777    4.743297    18.50638    21.14747
 Foreign |      22    24.77273     1.40951    6.611187    21.84149    27.70396
---------+--------------------------------------------------------------------
Combined |      74     21.2973    .6725511    5.785503     19.9569    22.63769
---------+--------------------------------------------------------------------
    diff |           -4.945804    1.362162               -7.661225   -2.230384
------------------------------------------------------------------------------
    diff = mean(Domestic) - mean(Foreign)                         t =  -3.6308
H0: diff = 0                                     Degrees of freedom =       72

    Ha: diff &lt; 0                 Ha: diff != 0                 Ha: diff &gt; 0
 Pr(T &lt; t) = 0.0003         Pr(|T| &gt; |t|) = 0.0005          Pr(T &gt; t) = 0.9997
</code></pre>
<p>The output is very similar to <a href="solutions.html#one-sample-t-test">above</a>. We get some descriptives by group, and combined, as well as a confidence interval for the difference. Notice that the null hypothesis (<code>Ho</code>) is simply 0 because we are testing whether the difference between the groups is statistically significant, regardless of the actual values of the means.</p>
<p>The p-values have the same interpretation, though in terms of the difference of means rather than just the means. More-so than even in the one-sided test, you should use the two-sided p-value, so our p-value is 0.0005. Just as a note, do not report this p-value as 0 if you round! Instead, report that the p-value is less than .01 or less than .001.</p>
<p>“There is less than a .1% chance that, if the average mileage was equivalent in domestic and foreign cars, we would observe a difference in the average mileage of 4.945804 or more.” Note that the sign of the difference doesn’t matter here because we’re looking at the two-sided version; the sign tells us that foreign cars in the sample have higher average mileage than domestic cars.</p>
<p>However, there is an additional assumption here that we neglected; namely that the variances of the two groups are equivalent. If you make this assumption, then the above analysis is sufficient. However, if you don’t make this assumption, you can instead run the two-sample t-test with unequal variances by adding the <code>unequal</code> option.</p>
<pre><code>. ttest mpg, by(foreign) unequal

Two-sample t test with unequal variances
------------------------------------------------------------------------------
   Group |     Obs        Mean    Std. err.   Std. dev.   [95% conf. interval]
---------+--------------------------------------------------------------------
Domestic |      52    19.82692     .657777    4.743297    18.50638    21.14747
 Foreign |      22    24.77273     1.40951    6.611187    21.84149    27.70396
---------+--------------------------------------------------------------------
Combined |      74     21.2973    .6725511    5.785503     19.9569    22.63769
---------+--------------------------------------------------------------------
    diff |           -4.945804    1.555438               -8.120053   -1.771556
------------------------------------------------------------------------------
    diff = mean(Domestic) - mean(Foreign)                         t =  -3.1797
H0: diff = 0                     Satterthwaite's degrees of freedom =  30.5463

    Ha: diff &lt; 0                 Ha: diff != 0                 Ha: diff &gt; 0
 Pr(T &lt; t) = 0.0017         Pr(|T| &gt; |t|) = 0.0034          Pr(T &gt; t) = 0.9983
</code></pre>
<p>The unequal test is slightly more conservative, but there has been some work (e.g.&nbsp;<a href="#citations">Delacre et al 2017</a>, <a href="#citations">Ruxton 2006</a>) showing that you should always use the unequal version.</p>
<p>The equal variance version (the first one we ran) is known as Student’s<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> t-test, and the unequal variance version (with the <code>unequal</code> option) is known as Welch’s t-test.</p>
<p>If you want to test whether the variance between the two groups is equal, you can use <code>sdtest</code> in a similar fashion to <code>ttest</code> (<code>sdtest mpg, by(foreign)</code>).</p>
<p><sup>###</sup> Paired</p>
<p>We noted in the assumptions above that we need the two groups to be independent. What if they aren’t? An example of paired data would include before-and-after measures or measures from two family members. In both cases, it is reasonable to assume the two measures from the same person or family are more similar than a measure from one person against a measure from another person.</p>
<p>The auto data set does not have a good example of paired data, so lets use the “bpwide” data instead.</p>
<pre><code>. sysuse bpwide, clear
(Fictional blood-pressure data)

. list in 1/5

     +-----------------------------------------------+
     | patient    sex   agegrp   bp_bef~e   bp_after |
     |-----------------------------------------------|
  1. |       1   Male    30-45        143        153 |
  2. |       2   Male    30-45        163        170 |
  3. |       3   Male    30-45        153        168 |
  4. |       4   Male    30-45        153        142 |
  5. |       5   Male    30-45        146        141 |
     +-----------------------------------------------+
</code></pre>
<p>We have measures from different patients, including a before and after measure of the blood pressure. We again use <code>ttest</code> to perform the test:</p>
<pre><code>. ttest bp_after == bp_before

Paired t test
------------------------------------------------------------------------------
Variable |     Obs        Mean    Std. err.   Std. dev.   [95% conf. interval]
---------+--------------------------------------------------------------------
bp_after |     120    151.3583    1.294234    14.17762    148.7956     153.921
bp_bef~e |     120      156.45    1.039746    11.38985    154.3912    158.5088
---------+--------------------------------------------------------------------
    diff |     120   -5.091667    1.525736     16.7136   -8.112776   -2.070557
------------------------------------------------------------------------------
     mean(diff) = mean(bp_after - bp_before)                      t =  -3.3372
 H0: mean(diff) = 0                              Degrees of freedom =      119

 Ha: mean(diff) &lt; 0           Ha: mean(diff) != 0           Ha: mean(diff) &gt; 0
 Pr(T &lt; t) = 0.0006         Pr(|T| &gt; |t|) = 0.0011          Pr(T &gt; t) = 0.9994
</code></pre>
<p>We see that the blood pressure after is slightly lower (151 vs 156), and the two-sided p-value is statistically significant!</p>
<p>While we technically used the paired t-test for this, behind the scenes, this is identical to generating a difference variable (e.g.&nbsp;post score - pre score) and performing the <a href="solutions.html#one-sample-t-test">one-sample t-test</a>:</p>
<pre><code>. gen bp_change = bp_after - bp_before

. ttest bp_change == 0

One-sample t test
------------------------------------------------------------------------------
Variable |     Obs        Mean    Std. err.   Std. dev.   [95% conf. interval]
---------+--------------------------------------------------------------------
bp_cha~e |     120   -5.091667    1.525736     16.7136   -8.112776   -2.070557
------------------------------------------------------------------------------
    mean = mean(bp_change)                                        t =  -3.3372
H0: mean = 0                                     Degrees of freedom =      119

    Ha: mean &lt; 0                 Ha: mean != 0                 Ha: mean &gt; 0
 Pr(T &lt; t) = 0.0006         Pr(|T| &gt; |t|) = 0.0011          Pr(T &gt; t) = 0.9994
</code></pre>
<p><sup>###</sup> Comparing Proportions</p>
<p>If you have a ordinal variable (a categorical variable that has an ordering to it), a t-test is often still appropriate<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. However, for binary variables, we should not use a regular t-test. Instead we use a Z-test<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>.</p>
<p>The command in stata is <code>prtest</code> and it functions identically to <code>ttest</code>:</p>
<p>One-sample: ~~~~ . webuse pneumoniacrt, clear (Bacterial pneumonia episodes data from CRT (Hayes and Moulton 2009))</p>
<p>. prtest pneumonia = .25</p>
<p>One-sample test of proportion Number of obs = 449</p>
<table class="table">
<colgroup>
<col style="width: 100%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Variable | Mean Std. err. [95% conf. interval] ————-+—————————————————————- pneumonia | .1959911 .0187338 .1592736 .2327086</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">p = proportion(pneumonia) z = -2.6429 H0: p = 0.25</td>
</tr>
<tr class="even">
<td style="text-align: right;">Ha: p &lt; 0.25 Ha: p != 0.25 Ha: p &gt; 0.25 Pr(Z &lt; z) = 0.0041 Pr(|Z| &gt; |z|) = 0.0082 Pr(Z &gt; z) = 0.9959</td>
</tr>
<tr class="odd">
<td style="text-align: right;">~~~~</td>
</tr>
<tr class="even">
<td style="text-align: right;">Independent two-sample: ~~~~ . prtest pneumonia, by(vaccine)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Two-sample test of proportions MnCC: Number of obs = 238 PnCRM7: Number of obs = 211</td>
</tr>
</tbody>
</table>
<pre><code>   Group |       Mean   Std. err.      z    P&gt;|z|     [95% conf. interval]</code></pre>
<p>————-+—————————————————————- MnCC | .2226891 .0269686 .1698316 .2755466 PnCRM7 | .1658768 .0256075 .1156871 .2160665 ————-+—————————————————————- diff | .0568123 .0371894 -.0160775 .1297021 | under H0: .0375355 1.51 0.130 —————————————————————————— diff = prop(MnCC) - prop(PnCRM7) z = 1.5136 H0: diff = 0</p>
<pre><code>Ha: diff &lt; 0                 Ha: diff != 0                 Ha: diff &gt; 0</code></pre>
<p>Pr(Z &lt; z) = 0.9349 Pr(|Z| &gt; |z|) = 0.1301 Pr(Z &gt; z) = 0.0651</p>
<pre><code>
Paired two-sample</code></pre>
<p>. sysuse bpwide, clear (Fictional blood-pressure data)</p>
<p>. gen bp_beforehigh = bp_before &gt; 160</p>
<p>. gen bp_afterhigh = bp_after &gt; 160</p>
<p>. list *high in 1/5</p>
<pre><code> +---------------------+
 | bp_bef~h   bp_aft~h |
 |---------------------|</code></pre>
<ol type="1">
<li><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0 0 |</p></li>
<li><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1 1 |</p></li>
<li><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0 1 |</p></li>
<li><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0 0 |</p></li>
<li><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0 0 |</p>
+———————+</li>
</ol>
<p>. prtest bp_afterhigh = bp_beforehigh</p>
<p>Two-sample test of proportions bp_afterhigh: Number of obs = 120 bp_beforehig: Number of obs = 120 —————————————————————————— Variable | Mean Std. err. z P&gt;|z| [95% conf. interval] ————-+—————————————————————- bp_afterhigh | .2583333 .039958 .180017 .3366496 bp_beforehig | .35 .0435412 .2646609 .4353391 ————-+—————————————————————- diff | -.0916667 .0590972 -.207495 .0241617 | under H0: .0593927 -1.54 0.123 —————————————————————————— diff = prop(bp_afterhigh) - prop(bp_beforehig) z = -1.5434 H0: diff = 0</p>
<pre><code>Ha: diff &lt; 0                 Ha: diff != 0                 Ha: diff &gt; 0</code></pre>
<p>Pr(Z &lt; z) = 0.0614 Pr(|Z| &gt; |z|) = 0.1227 Pr(Z &gt; z) = 0.9386</p>
<pre><code>


^#^^#^ Chi-square test

We've seen how to handle continuous and binary variables, and even some ordinal variables. However, if we want to look at a categorical variable which
is not binary and we cannot treat as continuous, we can instead use a ^$^\chi^2^$^ test (^$^\chi^$^ is a Greek letter which is spelled "chi" in
English, and rhymes with "why"). There are a few variations on the ^$^\chi^2^$^ test, the version we talk of here is a test of association, where we
are testing the null hypothesis that the distribution of one variable is the same at every level of another variable. Let's return to the auto data
set, and compare `rep78` (Repair Record 1978) and `foreign`. We'll start by looking at a crosstab.
</code></pre>
<p>. sysuse auto, clear (1978 automobile data)</p>
<p>. tab foreign rep78</p>
<pre><code>       |                   Repair record 1978</code></pre>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 72%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Car origin</th>
<th>1 2 3 4 5</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Domestic</td>
<td>2 8 27 9 2</td>
<td>48</td>
</tr>
<tr class="even">
<td>Foreign</td>
<td>0 0 3 9 9</td>
<td>21</td>
</tr>
</tbody>
</table>
<p>———–+——————————————————-+———- Total | 2 8 30 18 11 | 69</p>
<pre><code>
If you're not familiar with crosstabs, each cell represents the number of observations which fall into the category - for example, there are 8 cars
which are both Domestic and have a Repair Record of 2.

We can think of testing whether the association between these two variables exists from either direction - we can either ask "Is the probability of a
car having a specific repair record the same among domestic cars as among foreign cars", or "Is the probability of a car being foreign or domestic the
same across all levels of repair record". We test it by adding the `chi2` option to `tab`:
</code></pre>
<p>. tab foreign rep78, chi2</p>
<pre><code>       |                   Repair record 1978</code></pre>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 72%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Car origin</th>
<th>1 2 3 4 5</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Domestic</td>
<td>2 8 27 9 2</td>
<td>48</td>
</tr>
<tr class="even">
<td>Foreign</td>
<td>0 0 3 9 9</td>
<td>21</td>
</tr>
</tbody>
</table>
<p>———–+——————————————————-+———- Total | 2 8 30 18 11 | 69</p>
<pre><code>      Pearson chi2(4) =  27.2640   Pr = 0.000</code></pre>
<pre><code>
Here we can see that the p-value (`pr`) associated with the ^$^\chi^2\^$^ test is very low (less than .001, p-values are never 0^[Unless you're in a
pathological setting, i.e. you're testing whether the average height of a population is less than 6 feet, and somehow you get an average height of -20
feet....]!), so we can reject the null hypothesis and claim there is evidence of a statistically significant association between `foreign` and
`rep78`.

Note that the ^$^\chi^2\^$^ test ignores scale - if we had 4,800 Domestic cars instead of 48, and the percentage at each Repair Record were the same
(e.g. instead of 8 Domestic cars with Repair Record of 2, we had 800), we would get the same test result.

Finally, the critiques [above](univariate-and-some-bivariate-analysis.html) about the lack of usefulness of t-tests extends to ^$^\chi^2^$^ tests as
well.

^#^^#^^#^ Fisher's Exact Test

However, we probably should not have performed a ^$^\chi^2^$^ test here. One important assumption of the ^$^\chi^2^$^ test is that the *expected*
count in each cell is at least 5. The expected count is the row total times the column total divided by the total number. For example, we looked at
the 8 vehicles that were domestic which a Repair Record of 2. The row total is the number of domestic cars (48) and the column total is the number of
cars with Repair Record of 2 (8), with a total of 69 cars overall (`rep78` has 5 missing values). Therefore, the expected count is

^$$^
    \frac{48*8}{69} = 5.565
^$$^

This passes the assumption. To emphasize - this passed because the *expected count* is above 5. The fact that the observed count (8) is above 5 plays
no role in this assumption.

Rather than manually calculating this for each entry, the `expected` option tells Stata to do it for us.
</code></pre>
<p>. tab foreign rep78, expected</p>
<table class="table">
<colgroup>
<col style="width: 29%">
</colgroup>
<tbody>
<tr class="odd">
<td><h2 id="key" data-number="3.1" class="anchored"><span class="header-section-number">3.1</span> Key</h2>
<pre><code> frequency</code></pre>
<p>expected frequency</p></td>
</tr>
</tbody>
</table>
<pre><code>       |                   Repair record 1978</code></pre>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 72%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Car origin</th>
<th>1 2 3 4 5</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Domestic</td>
<td>2 8 27 9 2</td>
<td>48</td>
</tr>
<tr class="even">
<td>1.4 5.6 20.9 12.5 7.7</td>
<td>48.0</td>
<td></td>
</tr>
</tbody>
</table>
<p>———–+——————————————————-+———- Foreign | 0 0 3 9 9 | 21 | 0.6 2.4 9.1 5.5 3.3 | 21.0 ———–+——————————————————-+———- Total | 2 8 30 18 11 | 69 | 2.0 8.0 30.0 18.0 11.0 | 69.0</p>
<pre><code>
We see that the assumption fails in a number of cells.

There are several possible solutions. One is to perform instead of a ^$^\chi^2^$^ test, use a Fisher's Exact test. Originally designed for 2x2 designs
(two binary variables), it can be carried out for any arbitrarily large crosstab - in theory. In practice, the calculation is simply too demanding for
large tables. This 2x5 table is fine, but for example, a 9x9 table would fail.
</code></pre>
<p>. tab foreign rep78, exact</p>
<p>Enumerating sample-space combinations: stage 5: enumerations = 1 stage 4: enumerations = 3 stage 3: enumerations = 24 stage 2: enumerations = 203 stage 1: enumerations = 0</p>
<pre><code>       |                   Repair record 1978</code></pre>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 72%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Car origin</th>
<th>1 2 3 4 5</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Domestic</td>
<td>2 8 27 9 2</td>
<td>48</td>
</tr>
<tr class="even">
<td>Foreign</td>
<td>0 0 3 9 9</td>
<td>21</td>
</tr>
</tbody>
</table>
<p>———–+——————————————————-+———- Total | 2 8 30 18 11 | 69</p>
<pre><code>       Fisher's exact =                 0.000</code></pre>
<p>~~~~</p>
<p>We obtain the same conclusion.</p>
<p>If your crosstab is too large for the exact test, you may need to consider rebinning or an entirely different analysis method such as some sort of regression such as <a href="regression.html#logistic-regression">logistic regression</a> if one of the variables was binary, or multinomial or ordinal regression if neither are binary. (Multinomial and ordinal regression will not be covered in this workshop.)</p>
<p><sup>##</sup> Exercise 3</p>
<p>Load up the NHANES data.</p>
<pre><code>sysuse nhanes2, clear</code></pre>
<ol type="1">
<li>We don’t care about normality assumptions here. Why?</li>
<li>The average height of all <em>men</em> in America is 5’9” (176 cm). Does this sample appear representative of this fact? (E.g. is there evidence that the average in the sample differs from this?)</li>
<li>We would expect height and weight to differ by gender. Is there any evidence that age does?</li>
<li>Take a look at a crosstab of <code>race</code> and <code>diabetes</code>. Does it look like the percentage of diabetics is the same across race? The <code>col</code> or <code>row</code> option might help here. Test this with a <sup><span class="math inline">\(^\chi^2^\)</span></sup> test.</li>
</ol>
<p><sup>##</sup> Citations</p>
<ul>
<li>Delacre, Marie, Daniël Lakens, and Christophe Leys. “Why Psychologists Should by Default Use Welch’s t-test Instead of Student’s t-test.” International Review of Social Psychology 30.1 (2017).</li>
<li>Ruxton, Graeme D. “The unequal variance t-test is an underused alternative to Student’s t-test and the Mann–Whitney U test.” Behavioral Ecology 17.4 (2006): 688-690.</li>
</ul>


<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>This is by the <a href="https://en.wikipedia.org/wiki/Central_limit_theorem">central limit theorem</a>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Named not for students in a class, but the pseudonym for statistician <a href="https://en.wikipedia.org/wiki/William_Sealy_Gosset">William Sealy Gosset</a>. Gosset worked at the Guinness brewery when he was performing some of his seminal work and wasn’t allowed to publish under his own name, so he used the pseudonym Student.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>This requires the assumption that the ordinal variable can be well approximated by a continuous variable. This assumption is fine if each level of the ordinal variable is “equally” spaced (e.g.&nbsp;the amount of “effort” to go from level 1 to level 2 is the same as from level 4 to level 5).<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The statistical reasoning is that when we’re dealing with proportions, the variance is determined directly by the mean. A t-test assumes we need to estimate the variance as well. A Z-test assumes we know the variance, which will be more efficient.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./02-visualization.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">02-visualization.html</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04-regression.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">_cons | 5.113759 4.889846 1.05 0.299 -4.636317 14.86384</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>